apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-api-test
spec:
  destination:
    namespace: vote-test
    server: https://kubernetes.default.svc
  project: xfteam1
  source:
    path: k8s/openshift/base
    repoURL: 'https://github.com/jwennerberg/vote-api.git'
    targetRevision: HEAD
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
