apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote-api-dev
spec:
  destination:
    namespace: vote-dev
    server: https://kubernetes.default.svc
  project: vote
  source:
    path: k8s/openshift/dev
    repoURL: 'https://github.com/jwennerberg/vote-api.git'
    targetRevision: HEAD
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /spec/triggers/0/imageChange
